/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;


import java.util.logging.Level;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class App {

    private static SessionFactory sessionFactory;

    public App() {
        // this will load the hibernate.cfg.xml file with all the configuration
        Configuration configuration = new Configuration().configure();
        sessionFactory = configuration.buildSessionFactory();
    }

    public static void main(String[] args) {
        java.util.logging.Logger.getLogger("org.hibernate").setLevel(Level.SEVERE);
        
    }
}
